#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/yum-updatesd" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d yum-updatesd stop || exit $?
	else
		/etc/init.d/yum-updatesd stop || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
	update-python-modules -c  yum.public yum.private
fi
# End automatically added section
