#!/bin/sh
#
# yum   Yum updates daemon.
#
#       Written by Andres Salomon <dilinger@debian.org>
#
### BEGIN INIT INFO
# Provides:          yum-updatesd
# Required-Start:
# Required-Stop:
# Should-Start:      $syslog $network $local_fs
# Should-Stop:       $syslog $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Yum updates daemon
# Description:       yum-updatesd is a daemon which periodically checks for
#                    (rpm) package updates, and can send notifications via
#                    mail, dbus, or syslog.
### END INIT INFO

DAEMON=/usr/sbin/yum-updatesd
NAME=yum-updatesd
DESC=yum-updatesd
CONFIG=/etc/yum/yum-updatesd.conf
PIDFILE=/var/run/yum-updatesd.pid

# Exit if START_YUM_UPDATESD is not "yes" in /etc/default/yum-updatesd
if [ -f /etc/default/yum-updatesd ] ; then
	. /etc/default/yum-updatesd
fi
if ! [ "${START_YUM_UPDATESD}" = yes ] ; then
	exit 0
fi

test -f $DAEMON || exit 0
test -f $CONFIG || exit 0

. /lib/lsb/init-functions

case "$1" in
start)
	log_daemon_msg "Starting $DESC" "$NAME"
	start-stop-daemon --start --quiet --pidfile $PIDFILE \
			--nicelevel 19 --exec $DAEMON
	log_end_msg $?
	;;
stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
			--exec $DAEMON
        log_end_msg $?
        ;;
restart)
	log_daemon_msg "Restarting $DESC" "$NAME"
        start-stop-daemon --stop --retry 5 --quiet --pidfile $PIDFILE \
			--exec $DAEMON
        start-stop-daemon --start --quiet --pidfile $PIDFILE \
			--nicelevel 19 --exec $DAEMON
        log_end_msg $?
        ;;
reload|force-reload)
	log_daemon_msg "Reloading configuration files for $DESC" "$NAME"
	if start-stop-daemon --stop --quiet --signal 1 --pidfile $PIDFILE \
			--exec $DAEMON; then
		log_end_msg 0
	else
		log_action_end_msg 1
	fi
        ;;
*)
	log_action_msg "Usage: /etc/init.d/$NAME {start|stop|restart|reload|force-reload}" >&2
        exit 2
        ;;
esac

exit 0
